export const categories = [
  { id: "all", name: "全部", nameEn: "All", nameJa: "すべて", icon: "🍜" },
  { id: "combo", name: "套餐", nameEn: "Combo Sets", nameJa: "セット", icon: "🍱" },
  { id: "tonkotsu", name: "豚骨拉面", nameEn: "Tonkotsu Ramen", nameJa: "豚骨ラーメン", icon: "🍥" },
  { id: "shoyu", name: "酱油拉面", nameEn: "Shoyu Ramen", nameJa: "醤油ラーメン", icon: "🥢" },
  { id: "miso", name: "味噌拉面", nameEn: "Miso Ramen", nameJa: "味噌ラーメン", icon: "🧈" },
  { id: "tsukemen", name: "蘸面", nameEn: "Tsukemen", nameJa: "つけ麺", icon: "🍲" },
  { id: "sides", name: "小食", nameEn: "Sides", nameJa: "サイド", icon: "🥟" },
  { id: "drinks", name: "饮料", nameEn: "Drinks", nameJa: "ドリンク", icon: "🍺" },
]

export const products = [
  // 套餐商品
  {
    id: 101,
    name: "豚骨拉面经典套餐",
    nameEn: "Tonkotsu Ramen Classic Set",
    nameJa: "豚骨ラーメン定番セット",
    description: "特制豚骨拉面+煎饺(5个)+日式啤酒+海苔",
    descriptionEn: "Special Tonkotsu Ramen + Gyoza (5pcs) + Japanese Beer + Nori",
    descriptionJa: "特製豚骨ラーメン+餃子(5個)+日本ビール+海苔",
    image: "/combo-tonkotsu-set.png",
    category: "combo",
    rating: 4.9,
    sales: "月销3456",
    salesEn: "3456 sold",
    salesJa: "月間3456個",
    badges: ["超值", "推荐"],
    badgesEn: ["Great Value", "Recommended"],
    badgesJa: ["お得", "おすすめ"],
    isPopular: true,
    specs: [
      {
        id: "tonkotsu-combo-regular",
        name: "标准套餐",
        nameEn: "Regular Set",
        nameJa: "レギュラーセット",
        price: "68.0",
        priceEn: "9.8",
        priceJa: "1280",
        originalPrice: "78.0",
        isDefault: true,
      },
      {
        id: "tonkotsu-combo-large",
        name: "大份套餐",
        nameEn: "Large Set",
        nameJa: "大盛セット",
        price: "75.0",
        priceEn: "10.8",
        priceJa: "1420",
        originalPrice: "87.0",
      },
    ],
  },
  {
    id: 102,
    name: "味噌拉面温馨套餐",
    nameEn: "Miso Ramen Comfort Set",
    nameJa: "味噌ラーメン温かセット",
    description: "味噌拉面+叉烧饭+绿茶+腌菜",
    descriptionEn: "Miso Ramen + Chashu Rice + Green Tea + Pickles",
    descriptionJa: "味噌ラーメン+チャーシュー丼+緑茶+お漬物",
    image: "/combo-miso-set.png",
    category: "combo",
    rating: 4.8,
    sales: "月销2567",
    salesEn: "2567 sold",
    salesJa: "月間2567個",
    badges: ["温馨", "家常"],
    badgesEn: ["Comfort", "Homestyle"],
    badgesJa: ["温かい", "家庭的"],
    isPopular: true,
    specs: [
      {
        id: "miso-combo-regular",
        name: "标准套餐",
        nameEn: "Regular Set",
        nameJa: "レギュラーセット",
        price: "62.0",
        priceEn: "8.9",
        priceJa: "1150",
        originalPrice: "75.0",
        isDefault: true,
      },
      {
        id: "miso-combo-large",
        name: "大份套餐",
        nameEn: "Large Set",
        nameJa: "大盛セット",
        price: "70.0",
        priceEn: "10.0",
        priceJa: "1290",
        originalPrice: "85.0",
      },
    ],
  },
  {
    id: 103,
    name: "双人分享套餐",
    nameEn: "Couple Share Set",
    nameJa: "カップルシェアセット",
    description: "豚骨拉面+味噌拉面+煎饺(8个)+炸鸡块(6个)+啤酒(2瓶)",
    descriptionEn: "Tonkotsu + Miso Ramen + Gyoza (8pcs) + Fried Chicken (6pcs) + Beer (2 bottles)",
    descriptionJa: "豚骨+味噌ラーメン+餃子(8個)+唐揚げ(6個)+ビール(2本)",
    image: "/combo-couple-set.png",
    category: "combo",
    rating: 4.7,
    sales: "月销1876",
    salesEn: "1876 sold",
    salesJa: "月間1876個",
    badges: ["双人", "分享"],
    badgesEn: ["For Two", "Sharing"],
    badgesJa: ["二人用", "シェア"],
    isPopular: false,
    specs: [
      {
        id: "couple-combo",
        name: "双人套餐",
        nameEn: "Couple Set",
        nameJa: "カップルセット",
        price: "128.0",
        priceEn: "18.5",
        priceJa: "2380",
        originalPrice: "156.0",
        isDefault: true,
      },
    ],
  },
  {
    id: 104,
    name: "蘸面豪华套餐",
    nameEn: "Tsukemen Deluxe Set",
    nameJa: "つけ麺デラックスセット",
    description: "蘸面+烧肉饭+海苔手卷(2个)+抹茶拿铁",
    descriptionEn: "Tsukemen + Yakiniku Rice + Nori Hand Roll (2pcs) + Matcha Latte",
    descriptionJa: "つけ麺+焼肉丼+海苔手巻き(2個)+抹茶ラテ",
    image: "/combo-tsukemen-set.png",
    category: "combo",
    rating: 4.6,
    sales: "月销1234",
    salesEn: "1234 sold",
    salesJa: "月間1234個",
    badges: ["豪华", "精选"],
    badgesEn: ["Deluxe", "Premium"],
    badgesJa: ["デラックス", "厳選"],
    isPopular: false,
    specs: [
      {
        id: "tsukemen-deluxe",
        name: "豪华套餐",
        nameEn: "Deluxe Set",
        nameJa: "デラックスセット",
        price: "85.0",
        priceEn: "12.2",
        priceJa: "1580",
        originalPrice: "107.0",
        isDefault: true,
      },
    ],
  },
  {
    id: 105,
    name: "家庭欢乐套餐",
    nameEn: "Family Happy Set",
    nameJa: "ファミリーハッピーセット",
    description: "豚骨拉面(2碗)+酱油拉面(1碗)+煎饺(10个)+炸鸡块(10个)+饮料(3杯)",
    descriptionEn: "Tonkotsu Ramen (2) + Shoyu Ramen (1) + Gyoza (10pcs) + Fried Chicken (10pcs) + Drinks (3)",
    descriptionJa: "豚骨ラーメン(2杯)+醤油ラーメン(1杯)+餃子(10個)+唐揚げ(10個)+ドリンク(3杯)",
    image: "/combo-family-set.png",
    category: "combo",
    rating: 4.8,
    sales: "月销876",
    salesEn: "876 sold",
    salesJa: "月間876個",
    badges: ["家庭", "分量足"],
    badgesEn: ["Family", "Large Portion"],
    badgesJa: ["ファミリー", "大容量"],
    isPopular: false,
    specs: [
      {
        id: "family-combo",
        name: "家庭套餐",
        nameEn: "Family Set",
        nameJa: "ファミリーセット",
        price: "168.0",
        priceEn: "24.2",
        priceJa: "3120",
        originalPrice: "208.0",
        isDefault: true,
      },
    ],
  },
  {
    id: 106,
    name: "清爽夏日套餐",
    nameEn: "Refreshing Summer Set",
    nameJa: "さっぱり夏セット",
    description: "冷面+海苔手卷(4个)+绿茶+柠檬汽水",
    descriptionEn: "Cold Ramen + Nori Hand Roll (4pcs) + Green Tea + Lemon Soda",
    descriptionJa: "冷やし中華+海苔手巻き(4個)+緑茶+レモンソーダ",
    image: "/combo-summer-set.png",
    category: "combo",
    rating: 4.4,
    sales: "月销567",
    salesEn: "567 sold",
    salesJa: "月間567個",
    badges: ["清爽", "夏日"],
    badgesEn: ["Refreshing", "Summer"],
    badgesJa: ["さっぱり", "夏限定"],
    isPopular: false,
    specs: [
      {
        id: "summer-combo",
        name: "夏日套餐",
        nameEn: "Summer Set",
        nameJa: "夏セット",
        price: "58.0",
        priceEn: "8.3",
        priceJa: "1080",
        originalPrice: "71.0",
        isDefault: true,
      },
    ],
  },
  // 单品
  {
    id: 1,
    name: "特制豚骨拉面",
    nameEn: "Special Tonkotsu Ramen",
    nameJa: "特製豚骨ラーメン",
    description: "浓郁豚骨汤底+叉烧+溏心蛋+笋干",
    descriptionEn: "Rich tonkotsu broth + chashu + soft-boiled egg + bamboo shoots",
    descriptionJa: "濃厚豚骨スープ+チャーシュー+半熟卵+メンマ",
    image: "/tonkotsu-ramen-special.png",
    category: "tonkotsu",
    rating: 4.9,
    sales: "月销2156",
    salesEn: "2156 sold",
    salesJa: "月間2156個",
    badges: ["招牌"],
    badgesEn: ["Signature"],
    badgesJa: ["看板"],
    isPopular: true,
    specs: [
      {
        id: "tonkotsu-special-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "45.0",
        priceEn: "6.5",
        priceJa: "850",
        isDefault: true,
      },
      {
        id: "tonkotsu-special-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "52.0",
        priceEn: "7.5",
        priceJa: "980",
      },
      {
        id: "tonkotsu-special-extra",
        name: "特大份",
        nameEn: "Extra Large",
        nameJa: "特盛",
        price: "58.0",
        priceEn: "8.3",
        priceJa: "1080",
      },
    ],
  },
  {
    id: 2,
    name: "味噌拉面",
    nameEn: "Miso Ramen",
    nameJa: "味噌ラーメン",
    description: "北海道味噌汤底+玉米+叉烧+海苔",
    descriptionEn: "Hokkaido miso broth + corn + chashu + nori",
    descriptionJa: "北海道味噌スープ+コーン+チャーシュー+海苔",
    image: "/spicy-miso-ramen.png",
    category: "miso",
    rating: 4.7,
    sales: "月销1834",
    salesEn: "1834 sold",
    salesJa: "月間1834個",
    badges: ["浓郁"],
    badgesEn: ["Rich"],
    badgesJa: ["濃厚"],
    isPopular: true,
    specs: [
      {
        id: "miso-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "42.0",
        priceEn: "6.0",
        priceJa: "780",
        isDefault: true,
      },
      {
        id: "miso-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "48.0",
        priceEn: "6.9",
        priceJa: "890",
      },
    ],
  },
  {
    id: 3,
    name: "酱油拉面",
    nameEn: "Shoyu Ramen",
    nameJa: "醤油ラーメン",
    description: "清淡酱油汤底+叉烧+笋干+葱花",
    descriptionEn: "Light shoyu broth + chashu + bamboo shoots + scallions",
    descriptionJa: "あっさり醤油スープ+チャーシュー+メンマ+ネギ",
    image: "/shoyu-ramen.png",
    category: "shoyu",
    rating: 4.6,
    sales: "月销1456",
    salesEn: "1456 sold",
    salesJa: "月間1456個",
    badges: ["清爽"],
    badgesEn: ["Light"],
    badgesJa: ["あっさり"],
    isPopular: false,
    specs: [
      {
        id: "shoyu-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "38.0",
        priceEn: "5.5",
        priceJa: "720",
        isDefault: true,
      },
      {
        id: "shoyu-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "44.0",
        priceEn: "6.3",
        priceJa: "820",
      },
    ],
  },
  {
    id: 4,
    name: "蘸面",
    nameEn: "Tsukemen",
    nameJa: "つけ麺",
    description: "浓厚蘸汁+粗面条+叉烧+溏心蛋",
    descriptionEn: "Rich dipping sauce + thick noodles + chashu + soft-boiled egg",
    descriptionJa: "濃厚つけ汁+太麺+チャーシュー+半熟卵",
    image: "/tsukemen.png",
    category: "tsukemen",
    rating: 4.8,
    sales: "月销987",
    salesEn: "987 sold",
    salesJa: "月間987個",
    badges: ["特色"],
    badgesEn: ["Special"],
    badgesJa: ["特色"],
    isPopular: false,
    specs: [
      {
        id: "tsukemen-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "48.0",
        priceEn: "6.9",
        priceJa: "890",
        isDefault: true,
      },
      {
        id: "tsukemen-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "55.0",
        priceEn: "7.9",
        priceJa: "1020",
      },
    ],
  },
  {
    id: 5,
    name: "辣味噌拉面",
    nameEn: "Spicy Miso Ramen",
    nameJa: "辛味噌ラーメン",
    description: "辣味噌汤底+豆芽菜+叉烧+辣椒油",
    descriptionEn: "Spicy miso broth + bean sprouts + chashu + chili oil",
    descriptionJa: "辛味噌スープ+もやし+チャーシュー+ラー油",
    image: "/spicy-miso-ramen.png",
    category: "miso",
    rating: 4.5,
    sales: "月销756",
    salesEn: "756 sold",
    salesJa: "月間756個",
    badges: ["辣"],
    badgesEn: ["Spicy"],
    badgesJa: ["辛い"],
    isPopular: false,
    specs: [
      {
        id: "spicy-miso-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "44.0",
        priceEn: "6.3",
        priceJa: "820",
        isDefault: true,
      },
      {
        id: "spicy-miso-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "50.0",
        priceEn: "7.2",
        priceJa: "930",
      },
    ],
  },
  {
    id: 6,
    name: "煎饺",
    nameEn: "Gyoza",
    nameJa: "餃子",
    description: "香脆煎饺，猪肉韭菜馅",
    descriptionEn: "Crispy pan-fried dumplings with pork and chives",
    descriptionJa: "パリパリ焼き餃子、豚肉ニラ餡",
    image: "/gyoza.png",
    category: "sides",
    rating: 4.7,
    sales: "月销1234",
    salesEn: "1234 sold",
    salesJa: "月間1234個",
    badges: ["经典"],
    badgesEn: ["Classic"],
    badgesJa: ["定番"],
    isPopular: true,
    specs: [
      {
        id: "gyoza-5pcs",
        name: "5个装",
        nameEn: "5 pieces",
        nameJa: "5個",
        price: "18.0",
        priceEn: "2.6",
        priceJa: "420",
        isDefault: true,
      },
      {
        id: "gyoza-8pcs",
        name: "8个装",
        nameEn: "8 pieces",
        nameJa: "8個",
        price: "28.0",
        priceEn: "4.0",
        priceJa: "650",
      },
    ],
  },
  {
    id: 7,
    name: "叉烧饭",
    nameEn: "Chashu Rice Bowl",
    nameJa: "チャーシュー丼",
    description: "香嫩叉烧+白米饭+溏心蛋+海苔",
    descriptionEn: "Tender chashu + steamed rice + soft-boiled egg + nori",
    descriptionJa: "やわらかチャーシュー+白ご飯+半熟卵+海苔",
    image: "/chashu-rice-bowl.png",
    category: "sides",
    rating: 4.4,
    sales: "月销654",
    salesEn: "654 sold",
    salesJa: "月間654個",
    badges: [],
    badgesEn: [],
    badgesJa: [],
    isPopular: false,
    specs: [
      {
        id: "chashu-rice-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "25.0",
        priceEn: "3.6",
        priceJa: "580",
        isDefault: true,
      },
      {
        id: "chashu-rice-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "32.0",
        priceEn: "4.6",
        priceJa: "750",
      },
    ],
  },
  {
    id: 8,
    name: "日式啤酒",
    nameEn: "Japanese Beer",
    nameJa: "日本ビール",
    description: "冰爽日式啤酒，完美搭配拉面",
    descriptionEn: "Ice-cold Japanese beer, perfect with ramen",
    descriptionJa: "キンキンに冷えた日本ビール、ラーメンとの相性抜群",
    image: "/japanese-beer.png",
    category: "drinks",
    rating: 4.6,
    sales: "月销876",
    salesEn: "876 sold",
    salesJa: "月間876個",
    badges: [],
    badgesEn: [],
    badgesJa: [],
    isPopular: false,
    specs: [
      {
        id: "beer-330ml",
        name: "330ml",
        nameEn: "330ml",
        nameJa: "330ml",
        price: "15.0",
        priceEn: "2.2",
        priceJa: "350",
        isDefault: true,
      },
      {
        id: "beer-500ml",
        name: "500ml",
        nameEn: "500ml",
        nameJa: "500ml",
        price: "22.0",
        priceEn: "3.2",
        priceJa: "520",
      },
    ],
  },
  {
    id: 9,
    name: "黑蒜油拉面",
    nameEn: "Black Garlic Oil Ramen",
    nameJa: "黒ニンニク油ラーメン",
    description: "浓郁黑蒜油+豚骨汤底+叉烧+溏心蛋",
    descriptionEn: "Rich black garlic oil + tonkotsu broth + chashu + soft-boiled egg",
    descriptionJa: "濃厚黒ニンニク油+豚骨スープ+チャーシュー+半熟卵",
    image: "/black-garlic-ramen.png",
    category: "tonkotsu",
    rating: 4.8,
    sales: "月销1567",
    salesEn: "1567 sold",
    salesJa: "月間1567個",
    badges: ["浓郁"],
    badgesEn: ["Rich"],
    badgesJa: ["濃厚"],
    isPopular: true,
    specs: [
      {
        id: "black-garlic-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "48.0",
        priceEn: "6.9",
        priceJa: "890",
        isDefault: true,
      },
      {
        id: "black-garlic-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "55.0",
        priceEn: "7.9",
        priceJa: "1020",
      },
    ],
  },
  {
    id: 10,
    name: "盐味拉面",
    nameEn: "Shio Ramen",
    nameJa: "塩ラーメン",
    description: "清淡盐味汤底+海苔+笋干+葱花",
    descriptionEn: "Light salt broth + nori + bamboo shoots + scallions",
    descriptionJa: "あっさり塩スープ+海苔+メンマ+ネギ",
    image: "/shio-ramen.png",
    category: "shoyu",
    rating: 4.5,
    sales: "月销892",
    salesEn: "892 sold",
    salesJa: "月間892個",
    badges: ["清爽"],
    badgesEn: ["Light"],
    badgesJa: ["あっさり"],
    isPopular: false,
    specs: [
      {
        id: "shio-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "36.0",
        priceEn: "5.2",
        priceJa: "680",
        isDefault: true,
      },
      {
        id: "shio-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "42.0",
        priceEn: "6.0",
        priceJa: "780",
      },
    ],
  },
  {
    id: 11,
    name: "担担面",
    nameEn: "Tantanmen",
    nameJa: "担々麺",
    description: "四川风味芝麻汤底+肉末+青菜+花生",
    descriptionEn: "Sichuan-style sesame broth + minced pork + vegetables + peanuts",
    descriptionJa: "四川風ゴマスープ+肉そぼろ+青菜+ピーナッツ",
    image: "/tantanmen-sesame-ramen.png",
    category: "miso",
    rating: 4.6,
    sales: "月销1123",
    salesEn: "1123 sold",
    salesJa: "月間1123個",
    badges: ["辣", "特色"],
    badgesEn: ["Spicy", "Special"],
    badgesJa: ["辛い", "特色"],
    isPopular: false,
    specs: [
      {
        id: "tantanmen-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "46.0",
        priceEn: "6.6",
        priceJa: "850",
        isDefault: true,
      },
      {
        id: "tantanmen-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "52.0",
        priceEn: "7.5",
        priceJa: "960",
      },
    ],
  },
  {
    id: 12,
    name: "冷面",
    nameEn: "Cold Ramen",
    nameJa: "冷やし中華",
    description: "夏日特色冷面+黄瓜丝+火腿+鸡蛋丝",
    descriptionEn: "Summer special cold noodles + cucumber + ham + egg strips",
    descriptionJa: "夏の特色冷やし麺+キュウリ+ハム+錦糸卵",
    image: "/placeholder-0ak5c.png",
    category: "tsukemen",
    rating: 4.4,
    sales: "月销567",
    salesEn: "567 sold",
    salesJa: "月間567個",
    badges: ["清爽", "夏日"],
    badgesEn: ["Refreshing", "Summer"],
    badgesJa: ["さっぱり", "夏限定"],
    isPopular: false,
    specs: [
      {
        id: "cold-ramen-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "39.0",
        priceEn: "5.6",
        priceJa: "720",
        isDefault: true,
      },
    ],
  },
  {
    id: 13,
    name: "鸡白汤拉面",
    nameEn: "Chicken Paitan Ramen",
    nameJa: "鶏白湯ラーメン",
    description: "浓郁鸡白汤+鸡肉叉烧+溏心蛋+笋干",
    descriptionEn: "Rich chicken paitan + chicken chashu + soft-boiled egg + bamboo shoots",
    descriptionJa: "濃厚鶏白湯+鶏チャーシュー+半熟卵+メンマ",
    image: "/chicken-paitan-ramen.png",
    category: "tonkotsu",
    rating: 4.7,
    sales: "月销1345",
    salesEn: "1345 sold",
    salesJa: "月間1345個",
    badges: ["浓郁", "鸡汤"],
    badgesEn: ["Rich", "Chicken"],
    badgesJa: ["濃厚", "鶏スープ"],
    isPopular: true,
    specs: [
      {
        id: "chicken-paitan-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "43.0",
        priceEn: "6.2",
        priceJa: "800",
        isDefault: true,
      },
      {
        id: "chicken-paitan-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "49.0",
        priceEn: "7.0",
        priceJa: "910",
      },
    ],
  },
  {
    id: 14,
    name: "烧肉饭",
    nameEn: "Yakiniku Rice Bowl",
    nameJa: "焼肉丼",
    description: "香嫩烧肉+白米饭+泡菜+海苔",
    descriptionEn: "Tender grilled meat + steamed rice + pickles + nori",
    descriptionJa: "やわらか焼肉+白ご飯+キムチ+海苔",
    image: "/yakiniku-rice-bowl.png",
    category: "sides",
    rating: 4.5,
    sales: "月销789",
    salesEn: "789 sold",
    salesJa: "月間789個",
    badges: ["烧肉"],
    badgesEn: ["Grilled"],
    badgesJa: ["焼肉"],
    isPopular: false,
    specs: [
      {
        id: "yakiniku-rice-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "28.0",
        priceEn: "4.0",
        priceJa: "650",
        isDefault: true,
      },
      {
        id: "yakiniku-rice-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "35.0",
        priceEn: "5.0",
        priceJa: "820",
      },
    ],
  },
  {
    id: 15,
    name: "炸鸡块",
    nameEn: "Fried Chicken",
    nameJa: "唐揚げ",
    description: "酥脆炸鸡块，蘸料丰富",
    descriptionEn: "Crispy fried chicken with various dipping sauces",
    descriptionJa: "サクサク唐揚げ、各種タレ付き",
    image: "/crispy-fried-chicken.png",
    category: "sides",
    rating: 4.6,
    sales: "月销1456",
    salesEn: "1456 sold",
    salesJa: "月間1456個",
    badges: ["酥脆"],
    badgesEn: ["Crispy"],
    badgesJa: ["サクサク"],
    isPopular: true,
    specs: [
      {
        id: "fried-chicken-6pcs",
        name: "6块装",
        nameEn: "6 pieces",
        nameJa: "6個",
        price: "22.0",
        priceEn: "3.2",
        priceJa: "520",
        isDefault: true,
      },
      {
        id: "fried-chicken-10pcs",
        name: "10块装",
        nameEn: "10 pieces",
        nameJa: "10個",
        price: "35.0",
        priceEn: "5.0",
        priceJa: "820",
      },
    ],
  },
  {
    id: 16,
    name: "海苔手卷",
    nameEn: "Nori Hand Roll",
    nameJa: "海苔手巻き",
    description: "新鲜海苔+米饭+黄瓜+蟹棒",
    descriptionEn: "Fresh nori + rice + cucumber + crab stick",
    descriptionJa: "新鮮海苔+ご飯+キュウリ+カニカマ",
    image: "/nori-hand-roll.png",
    category: "sides",
    rating: 4.3,
    sales: "月销432",
    salesEn: "432 sold",
    salesJa: "月間432個",
    badges: ["清爽"],
    badgesEn: ["Fresh"],
    badgesJa: ["さっぱり"],
    isPopular: false,
    specs: [
      {
        id: "nori-roll-2pcs",
        name: "2个装",
        nameEn: "2 pieces",
        nameJa: "2個",
        price: "16.0",
        priceEn: "2.3",
        priceJa: "380",
        isDefault: true,
      },
      {
        id: "nori-roll-4pcs",
        name: "4个装",
        nameEn: "4 pieces",
        nameJa: "4個",
        price: "28.0",
        priceEn: "4.0",
        priceJa: "650",
      },
    ],
  },
  {
    id: 17,
    name: "绿茶",
    nameEn: "Green Tea",
    nameJa: "緑茶",
    description: "清香日式绿茶，热饮或冰饮",
    descriptionEn: "Fragrant Japanese green tea, hot or iced",
    descriptionJa: "香り高い日本緑茶、ホットまたはアイス",
    image: "/japanese-green-tea.png",
    category: "drinks",
    rating: 4.4,
    sales: "月销1234",
    salesEn: "1234 sold",
    salesJa: "月間1234個",
    badges: ["清香"],
    badgesEn: ["Fragrant"],
    badgesJa: ["香り高い"],
    isPopular: false,
    specs: [
      {
        id: "green-tea-hot",
        name: "热饮",
        nameEn: "Hot",
        nameJa: "ホット",
        price: "8.0",
        priceEn: "1.2",
        priceJa: "200",
        isDefault: true,
      },
      {
        id: "green-tea-iced",
        name: "冰饮",
        nameEn: "Iced",
        nameJa: "アイス",
        price: "10.0",
        priceEn: "1.4",
        priceJa: "250",
      },
    ],
  },
  {
    id: 18,
    name: "柠檬汽水",
    nameEn: "Lemon Soda",
    nameJa: "レモンソーダ",
    description: "清爽柠檬汽水，气泡丰富",
    descriptionEn: "Refreshing lemon soda with rich bubbles",
    descriptionJa: "さっぱりレモンソーダ、炭酸たっぷり",
    image: "/refreshing-cola.png",
    category: "drinks",
    rating: 4.2,
    sales: "月销678",
    salesEn: "678 sold",
    salesJa: "月間678個",
    badges: ["清爽"],
    badgesEn: ["Refreshing"],
    badgesJa: ["さっぱり"],
    isPopular: false,
    specs: [
      {
        id: "lemon-soda-regular",
        name: "标准杯",
        nameEn: "Regular",
        nameJa: "レギュラー",
        price: "12.0",
        priceEn: "1.7",
        priceJa: "280",
        isDefault: true,
      },
      {
        id: "lemon-soda-large",
        name: "大杯",
        nameEn: "Large",
        nameJa: "ラージ",
        price: "16.0",
        priceEn: "2.3",
        priceJa: "380",
      },
    ],
  },
  {
    id: 19,
    name: "乌龙茶",
    nameEn: "Oolong Tea",
    nameJa: "烏龍茶",
    description: "香醇乌龙茶，去油解腻",
    descriptionEn: "Mellow oolong tea, cuts through grease",
    descriptionJa: "まろやか烏龍茶、油っぽさを解消",
    image: "/japanese-green-tea.png",
    category: "drinks",
    rating: 4.3,
    sales: "月销543",
    salesEn: "543 sold",
    salesJa: "月間543個",
    badges: ["去腥"],
    badgesEn: ["Cleansing"],
    badgesJa: ["さっぱり"],
    isPopular: false,
    specs: [
      {
        id: "oolong-tea-bottle",
        name: "瓶装500ml",
        nameEn: "500ml Bottle",
        nameJa: "500mlボトル",
        price: "13.0",
        priceEn: "1.9",
        priceJa: "320",
        isDefault: true,
      },
    ],
  },
  {
    id: 20,
    name: "抹茶拿铁",
    nameEn: "Matcha Latte",
    nameJa: "抹茶ラテ",
    description: "浓郁抹茶+香滑牛奶，热饮或冰饮",
    descriptionEn: "Rich matcha + smooth milk, hot or iced",
    descriptionJa: "濃厚抹茶+なめらかミルク、ホットまたはアイス",
    image: "/japanese-green-tea.png",
    category: "drinks",
    rating: 4.7,
    sales: "月销987",
    salesEn: "987 sold",
    salesJa: "月間987個",
    badges: ["抹茶", "香滑"],
    badgesEn: ["Matcha", "Smooth"],
    badgesJa: ["抹茶", "なめらか"],
    isPopular: true,
    specs: [
      {
        id: "matcha-latte-hot",
        name: "热饮",
        nameEn: "Hot",
        nameJa: "ホット",
        price: "18.0",
        priceEn: "2.6",
        priceJa: "420",
        isDefault: true,
      },
      {
        id: "matcha-latte-iced",
        name: "冰饮",
        nameEn: "Iced",
        nameJa: "アイス",
        price: "20.0",
        priceEn: "2.9",
        priceJa: "480",
      },
    ],
  },
  {
    id: 21,
    name: "盐味拉面",
    nameEn: "Shio Ramen",
    nameJa: "塩ラーメン",
    description: "清淡盐味汤底+海苔+笋干+葱花",
    descriptionEn: "Light salt broth + nori + bamboo shoots + green onions",
    descriptionJa: "さっぱり塩スープ+海苔+メンマ+青ねぎ",
    image: "/shio-ramen.png",
    category: "shoyu",
    rating: 4.5,
    sales: "月销892",
    salesEn: "892 sold",
    salesJa: "月間892個",
    badges: ["清爽"],
    badgesEn: ["Light"],
    badgesJa: ["さっぱり"],
    isPopular: false,
    specs: [
      {
        id: "shio-ramen-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "36.0",
        priceEn: "5.2",
        priceJa: "680",
        isDefault: true,
      },
      {
        id: "shio-ramen-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "42.0",
        priceEn: "6.0",
        priceJa: "780",
      },
    ],
  },
  {
    id: 22,
    name: "辣味噌拉面",
    nameEn: "Spicy Miso Ramen",
    nameJa: "辛味噌ラーメン",
    description: "辣味噌汤底+豆芽菜+叉烧+辣椒油",
    descriptionEn: "Spicy miso broth + bean sprouts + chashu + chili oil",
    descriptionJa: "辛味噌スープ+もやし+チャーシュー+ラー油",
    image: "/spicy-miso-ramen.png",
    category: "miso",
    rating: 4.5,
    sales: "月销756",
    salesEn: "756 sold",
    salesJa: "月間756個",
    badges: ["辣"],
    badgesEn: ["Spicy"],
    badgesJa: ["辛い"],
    isPopular: false,
    specs: [
      {
        id: "spicy-miso-ramen-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "44.0",
        priceEn: "6.3",
        priceJa: "820",
        isDefault: true,
      },
      {
        id: "spicy-miso-ramen-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "50.0",
        priceEn: "7.2",
        priceJa: "920",
      },
    ],
  },
  {
    id: 23,
    name: "黑蒜油拉面",
    nameEn: "Black Garlic Ramen",
    nameJa: "黒ニンニクラーメン",
    description: "浓郁黑蒜油+豚骨汤底+叉烧+溏心蛋",
    descriptionEn: "Rich black garlic oil + tonkotsu broth + chashu + soft-boiled egg",
    descriptionJa: "濃厚黒ニンニクオイル+豚骨スープ+チャーシュー+半熟卵",
    image: "/black-garlic-ramen.png",
    category: "tonkotsu",
    rating: 4.8,
    sales: "月销1567",
    salesEn: "1567 sold",
    salesJa: "月間1567個",
    badges: ["浓郁"],
    badgesEn: ["Rich"],
    badgesJa: ["濃厚"],
    isPopular: true,
    specs: [
      {
        id: "black-garlic-ramen-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "48.0",
        priceEn: "6.9",
        priceJa: "890",
        isDefault: true,
      },
      {
        id: "black-garlic-ramen-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "54.0",
        priceEn: "7.8",
        priceJa: "990",
      },
    ],
  },
  {
    id: 24,
    name: "担担面",
    nameEn: "Tantanmen",
    nameJa: "坦々麺",
    description: "四川风味芝麻汤底+肉末+青菜+花生",
    descriptionEn: "Sichuan-style sesame broth + minced pork + greens + peanuts",
    descriptionJa: "四川風胡麻スープ+ひき肉+青菜+ピーナッツ",
    image: "/tantanmen-sesame-ramen.png",
    category: "tonkotsu",
    rating: 4.6,
    sales: "月销1123",
    salesEn: "1123 sold",
    salesJa: "月間1123個",
    badges: ["辣", "特色"],
    badgesEn: ["Spicy", "Special"],
    badgesJa: ["辛い", "特色"],
    isPopular: false,
    specs: [
      {
        id: "tantanmen-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "46.0",
        priceEn: "6.6",
        priceJa: "850",
        isDefault: true,
      },
      {
        id: "tantanmen-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "52.0",
        priceEn: "7.5",
        priceJa: "950",
      },
    ],
  },
  {
    id: 25,
    name: "鸡白汤拉面",
    nameEn: "Chicken Paitan Ramen",
    nameJa: "鶏白湯ラーメン",
    description: "浓郁鸡白汤+鸡肉叉烧+溏心蛋+笋干",
    descriptionEn: "Rich chicken paitan + chicken chashu + soft-boiled egg + bamboo shoots",
    descriptionJa: "濃厚鶏白湯+鶏チャーシュー+半熟卵+メンマ",
    image: "/chicken-paitan-ramen.png",
    category: "tonkotsu",
    rating: 4.7,
    sales: "月销1345",
    salesEn: "1345 sold",
    salesJa: "月間1345個",
    badges: ["浓郁", "鸡汤"],
    badgesEn: ["Rich", "Chicken"],
    badgesJa: ["濃厚", "鶏スープ"],
    isPopular: true,
    specs: [
      {
        id: "chicken-paitan-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "43.0",
        priceEn: "6.2",
        priceJa: "800",
        isDefault: true,
      },
      {
        id: "chicken-paitan-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "49.0",
        priceEn: "7.0",
        priceJa: "910",
      },
    ],
  },
  {
    id: 26,
    name: "烧肉饭",
    nameEn: "Yakiniku Rice Bowl",
    nameJa: "焼肉丼",
    description: "香嫩烧肉+白米饭+泡菜+海苔",
    descriptionEn: "Tender grilled meat + steamed rice + pickles + nori",
    descriptionJa: "やわらか焼肉+白ご飯+キムチ+海苔",
    image: "/yakiniku-rice-bowl.png",
    category: "sides",
    rating: 4.5,
    sales: "月销789",
    salesEn: "789 sold",
    salesJa: "月間789個",
    badges: ["烧肉"],
    badgesEn: ["Grilled"],
    badgesJa: ["焼肉"],
    isPopular: false,
    specs: [
      {
        id: "yakiniku-rice-regular",
        name: "标准份",
        nameEn: "Regular",
        nameJa: "並盛",
        price: "28.0",
        priceEn: "4.0",
        priceJa: "650",
        isDefault: true,
      },
      {
        id: "yakiniku-rice-large",
        name: "大份",
        nameEn: "Large",
        nameJa: "大盛",
        price: "35.0",
        priceEn: "5.0",
        priceJa: "780",
      },
    ],
  },
  {
    id: 27,
    name: "炸鸡块",
    nameEn: "Crispy Fried Chicken",
    nameJa: "唐揚げ",
    description: "酥脆炸鸡块，蘸料丰富",
    descriptionEn: "Crispy fried chicken pieces with dipping sauce",
    descriptionJa: "サクサク唐揚げ、タレ付き",
    image: "/crispy-fried-chicken.png",
    category: "sides",
    rating: 4.6,
    sales: "月销1456",
    salesEn: "1456 sold",
    salesJa: "月間1456個",
    badges: ["酥脆"],
    badgesEn: ["Crispy"],
    badgesJa: ["サクサク"],
    isPopular: true,
    specs: [
      {
        id: "fried-chicken-regular",
        name: "标准份(6块)",
        nameEn: "Regular (6pcs)",
        nameJa: "並盛(6個)",
        price: "22.0",
        priceEn: "3.2",
        priceJa: "520",
        isDefault: true,
      },
      {
        id: "fried-chicken-large",
        name: "大份(10块)",
        nameEn: "Large (10pcs)",
        nameJa: "大盛(10個)",
        price: "32.0",
        priceEn: "4.6",
        priceJa: "720",
      },
    ],
  },
  {
    id: 28,
    name: "海苔手卷",
    nameEn: "Nori Hand Roll",
    nameJa: "海苔手巻き",
    description: "新鲜海苔+米饭+黄瓜+蟹棒",
    descriptionEn: "Fresh nori + rice + cucumber + crab stick",
    descriptionJa: "新鮮海苔+ご飯+キュウリ+カニカマ",
    image: "/nori-hand-roll.png",
    category: "sides",
    rating: 4.3,
    sales: "月销432",
    salesEn: "432 sold",
    salesJa: "月間432個",
    badges: ["清爽"],
    badgesEn: ["Fresh"],
    badgesJa: ["さっぱり"],
    isPopular: false,
    specs: [
      {
        id: "nori-hand-roll-regular",
        name: "标准份(2个)",
        nameEn: "Regular (2pcs)",
        nameJa: "並盛(2個)",
        price: "16.0",
        priceEn: "2.3",
        priceJa: "380",
        isDefault: true,
      },
      {
        id: "nori-hand-roll-large",
        name: "大份(4个)",
        nameEn: "Large (4pcs)",
        nameJa: "大盛(4個)",
        price: "28.0",
        priceEn: "4.0",
        priceJa: "650",
      },
    ],
  },
  {
    id: 29,
    name: "绿茶",
    nameEn: "Green Tea",
    nameJa: "緑茶",
    description: "清香日式绿茶，热饮或冰饮",
    descriptionEn: "Fragrant Japanese green tea, hot or iced",
    descriptionJa: "香り高い日本緑茶、ホットまたはアイス",
    image: "/japanese-green-tea.png",
    category: "drinks",
    rating: 4.4,
    sales: "月销1234",
    salesEn: "1234 sold",
    salesJa: "月間1234個",
    badges: ["清香"],
    badgesEn: ["Fragrant"],
    badgesJa: ["香り高い"],
    isPopular: false,
    specs: [
      {
        id: "green-tea-hot",
        name: "热饮",
        nameEn: "Hot",
        nameJa: "ホット",
        price: "8.0",
        priceEn: "1.2",
        priceJa: "200",
        isDefault: true,
      },
      {
        id: "green-tea-iced",
        name: "冰饮",
        nameEn: "Iced",
        nameJa: "アイス",
        price: "10.0",
        priceEn: "1.4",
        priceJa: "250",
      },
    ],
  },
  {
    id: 30,
    name: "柠檬汽水",
    nameEn: "Lemon Soda",
    nameJa: "レモンソーダ",
    description: "清爽柠檬汽水，气泡丰富",
    descriptionEn: "Refreshing lemon soda with rich bubbles",
    descriptionJa: "さっぱりレモンソーダ、炭酸たっぷり",
    image: "/refreshing-cola.png",
    category: "drinks",
    rating: 4.2,
    sales: "月销678",
    salesEn: "678 sold",
    salesJa: "月間678個",
    badges: ["清爽"],
    badgesEn: ["Refreshing"],
    badgesJa: ["さっぱり"],
    isPopular: false,
    specs: [
      {
        id: "lemon-soda-regular",
        name: "标准杯",
        nameEn: "Regular",
        nameJa: "レギュラー",
        price: "12.0",
        priceEn: "1.7",
        priceJa: "280",
        isDefault: true,
      },
      {
        id: "lemon-soda-large",
        name: "大杯",
        nameEn: "Large",
        nameJa: "ラージ",
        price: "16.0",
        priceEn: "2.3",
        priceJa: "380",
      },
    ],
  },
  {
    id: 31,
    name: "乌龙茶",
    nameEn: "Oolong Tea",
    nameJa: "烏龍茶",
    description: "香醇乌龙茶，去油解腻",
    descriptionEn: "Mellow oolong tea, cuts through grease",
    descriptionJa: "まろやか烏龍茶、油っぽさを解消",
    image: "/japanese-green-tea.png",
    category: "drinks",
    rating: 4.3,
    sales: "月销543",
    salesEn: "543 sold",
    salesJa: "月間543個",
    badges: ["去腥"],
    badgesEn: ["Cleansing"],
    badgesJa: ["さっぱり"],
    isPopular: false,
    specs: [
      {
        id: "oolong-tea-bottle",
        name: "瓶装500ml",
        nameEn: "500ml Bottle",
        nameJa: "500mlボトル",
        price: "13.0",
        priceEn: "1.9",
        priceJa: "320",
        isDefault: true,
      },
    ],
  },
  {
    id: 32,
    name: "抹茶拿铁",
    nameEn: "Matcha Latte",
    nameJa: "抹茶ラテ",
    description: "浓郁抹茶+香滑牛奶，热饮或冰饮",
    descriptionEn: "Rich matcha + smooth milk, hot or iced",
    descriptionJa: "濃厚抹茶+なめらかミルク、ホットまたはアイス",
    image: "/japanese-green-tea.png",
    category: "drinks",
    rating: 4.7,
    sales: "月销987",
    salesEn: "987 sold",
    salesJa: "月間987個",
    badges: ["抹茶", "香滑"],
    badgesEn: ["Matcha", "Smooth"],
    badgesJa: ["抹茶", "なめらか"],
    isPopular: true,
    specs: [
      {
        id: "matcha-latte-hot",
        name: "热饮",
        nameEn: "Hot",
        nameJa: "ホット",
        price: "18.0",
        priceEn: "2.6",
        priceJa: "420",
        isDefault: true,
      },
      {
        id: "matcha-latte-iced",
        name: "冰饮",
        nameEn: "Iced",
        nameJa: "アイス",
        price: "20.0",
        priceEn: "2.9",
        priceJa: "480",
      },
    ],
  },
]

export const sideItems = [
  {
    id: "gyoza",
    name: "煎饺",
    nameEn: "Gyoza",
    nameJa: "餃子",
    price: "18.0",
    priceEn: "2.6",
    priceJa: "420",
    image: "/gyoza.png",
    description: "5个装，香脆煎饺",
    descriptionEn: "5 pieces, crispy pan-fried",
    descriptionJa: "5個、パリパリ焼き餃子",
  },
  {
    id: "chashu-rice",
    name: "叉烧饭",
    nameEn: "Chashu Rice",
    nameJa: "チャーシュー丼",
    price: "25.0",
    priceEn: "3.6",
    priceJa: "580",
    image: "/chashu-rice-bowl.png",
    description: "香嫩叉烧配白米饭",
    descriptionEn: "Tender chashu with steamed rice",
    descriptionJa: "やわらかチャーシューと白ご飯",
  },
  {
    id: "japanese-beer",
    name: "日式啤酒",
    nameEn: "Japanese Beer",
    nameJa: "日本ビール",
    price: "15.0",
    priceEn: "2.2",
    priceJa: "350",
    image: "/japanese-beer.png",
    description: "330ml，冰爽啤酒",
    descriptionEn: "330ml, ice-cold beer",
    descriptionJa: "330ml、キンキンビール",
  },
]

export const nearbyStores = [
  {
    id: 1,
    name: "一兰拉面(涩谷店)",
    nameEn: "Ichiran Ramen (Shibuya)",
    nameJa: "一蘭ラーメン（渋谷店）",
    address: "东京都涩谷区道玄坂1-2-3",
    addressEn: "1-2-3 Dogenzaka, Shibuya-ku, Tokyo",
    addressJa: "東京都渋谷区道玄坂1-2-3",
    distance: "0.8km",
    status: "operating",
    deliveryTime: "25-35分钟",
    deliveryTimeEn: "25-35 mins",
    deliveryTimeJa: "25-35分",
    pickupTime: "15-20分钟",
    pickupTimeEn: "15-20 mins",
    pickupTimeJa: "15-20分",
    isOpen: true,
  },
  {
    id: 2,
    name: "博多风龙拉面(新宿店)",
    nameEn: "Hakata Furyu Ramen (Shinjuku)",
    nameJa: "博多風龍ラーメン（新宿店）",
    address: "东京都新宿区歌舞伎町1-1-1",
    addressEn: "1-1-1 Kabukicho, Shinjuku-ku, Tokyo",
    addressJa: "東京都新宿区歌舞伎町1-1-1",
    distance: "1.2km",
    status: "operating",
    deliveryTime: "30-40分钟",
    deliveryTimeEn: "30-40 mins",
    deliveryTimeJa: "30-40分",
    pickupTime: "20-25分钟",
    pickupTimeEn: "20-25 mins",
    pickupTimeJa: "20-25分",
    isOpen: true,
  },
  {
    id: 3,
    name: "麦当劳(三里屯店)", // This was a McDonald's store, keeping it for now but it should be ramen
    nameEn: "McDonald's (Sanlitun)",
    nameJa: "マクドナルド（三里屯店）",
    address: "北京市朝阳区三里屯路19号",
    addressEn: "No. 19 Sanlitun Road, Chaoyang District, Beijing",
    addressJa: "北京市朝陽区三里屯路19号",
    distance: "2.1km",
    status: "closed",
    deliveryTime: "8-12分钟",
    deliveryTimeEn: "8-12 mins",
    deliveryTimeJa: "8-12分",
    pickupTime: "10-15分钟",
    pickupTimeEn: "10-15 mins",
    pickupTimeJa: "10-15分",
    isOpen: false,
  },
]

export const currentAddress = {
  name: "东京都涩谷区道玄坂1-2-3",
  nameEn: "1-2-3 Dogenzaka, Shibuya-ku, Tokyo",
  nameJa: "東京都渋谷区道玄坂1-2-3",
  detail: "涩谷大厦 8楼",
  detailEn: "Shibuya Building 8F",
  detailJa: "渋谷ビル 8階",
}
