name: Fast Deploy to K3s

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/ci.yml'
      - 'tests/**'
      - 'docs/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  fast-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 设置超时时间
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=moby/buildkit:v0.12.0

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha,scope=la-mian-fast
        cache-to: type=gha,mode=max,scope=la-mian-fast
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to K3s
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        
        # 创建命名空间（如果不存在）
        kubectl create namespace la-mian --dry-run=client -o yaml | kubectl apply -f -
        
        # 更新 Kubernetes 部署
        kubectl set image deployment/la-mian-app la-mian=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -n la-mian
        
        # 等待部署完成（快速超时）
        kubectl rollout status deployment/la-mian-app -n la-mian --timeout=60s

    - name: Quick Status Check
      run: |
        export KUBECONFIG=kubeconfig.yaml
        kubectl get pods -n la-mian --no-headers | grep -v "Running\|Completed" && exit 1 || echo "✅ Deployment successful" 